#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Blurate.Resource", IsApplication=true)]

namespace Blurate
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Cloo.Resource.String.ApplicationName = global::Blurate.Resource.String.ApplicationName;
			global::Cloo.Resource.String.Hello = global::Blurate.Resource.String.Hello;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int country_arrays = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int changeCam = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Milkmaid = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int rotateCam = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int rotCam = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int rotCam2 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int rotCam3 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int snapCam2 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int snapicon = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080005
			public const int bottomRel = 2131230725;
			
			// aapt resource value: 0x7f080003
			public const int camButton = 2131230723;
			
			// aapt resource value: 0x7f08000b
			public const int current_kernel = 2131230731;
			
			// aapt resource value: 0x7f080018
			public const int extract_visible_bitmap = 2131230744;
			
			// aapt resource value: 0x7f080008
			public const int importButton = 2131230728;
			
			// aapt resource value: 0x7f080000
			public const int iv_blank = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int iv_photo = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int iv_surf = 2131230722;
			
			// aapt resource value: 0x7f080017
			public const int menu_matrix_capture = 2131230743;
			
			// aapt resource value: 0x7f080016
			public const int menu_matrix_restore = 2131230742;
			
			// aapt resource value: 0x7f08000d
			public const int menu_scale_fit_center = 2131230733;
			
			// aapt resource value: 0x7f08000f
			public const int menu_scale_fit_end = 2131230735;
			
			// aapt resource value: 0x7f08000e
			public const int menu_scale_fit_start = 2131230734;
			
			// aapt resource value: 0x7f080010
			public const int menu_scale_fit_xy = 2131230736;
			
			// aapt resource value: 0x7f080015
			public const int menu_scale_random = 2131230741;
			
			// aapt resource value: 0x7f080014
			public const int menu_scale_random_animate = 2131230740;
			
			// aapt resource value: 0x7f080011
			public const int menu_scale_scale_center = 2131230737;
			
			// aapt resource value: 0x7f080012
			public const int menu_scale_scale_center_crop = 2131230738;
			
			// aapt resource value: 0x7f080013
			public const int menu_scale_scale_center_inside = 2131230739;
			
			// aapt resource value: 0x7f08000c
			public const int menu_zoom_toggle = 2131230732;
			
			// aapt resource value: 0x7f080006
			public const int myButton = 2131230726;
			
			// aapt resource value: 0x7f080009
			public const int myShareButton = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int snapButton = 2131230730;
			
			// aapt resource value: 0x7f080007
			public const int spinner1 = 2131230727;
			
			// aapt resource value: 0x7f080004
			public const int tv_current_matrix = 2131230724;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int main_menu = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int country_prompt = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int main_krnls = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int provider_paths = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
