#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Blurate.Resource", IsApplication=true)]

namespace Blurate
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Cloo.Resource.String.ApplicationName = global::Blurate.Resource.String.ApplicationName;
			global::Cloo.Resource.String.Hello = global::Blurate.Resource.String.Hello;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int country_arrays = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int changeCam = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Milkmaid = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int rotateCam = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int rotCam = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int rotCam2 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int rotCam3 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int snapCam2 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int snapicon = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070005
			public const int bottomRel = 2131165189;
			
			// aapt resource value: 0x7f070003
			public const int camButton = 2131165187;
			
			// aapt resource value: 0x7f07000b
			public const int current_kernel = 2131165195;
			
			// aapt resource value: 0x7f070018
			public const int extract_visible_bitmap = 2131165208;
			
			// aapt resource value: 0x7f070008
			public const int importButton = 2131165192;
			
			// aapt resource value: 0x7f070000
			public const int iv_blank = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int iv_photo = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int iv_surf = 2131165186;
			
			// aapt resource value: 0x7f070017
			public const int menu_matrix_capture = 2131165207;
			
			// aapt resource value: 0x7f070016
			public const int menu_matrix_restore = 2131165206;
			
			// aapt resource value: 0x7f07000d
			public const int menu_scale_fit_center = 2131165197;
			
			// aapt resource value: 0x7f07000f
			public const int menu_scale_fit_end = 2131165199;
			
			// aapt resource value: 0x7f07000e
			public const int menu_scale_fit_start = 2131165198;
			
			// aapt resource value: 0x7f070010
			public const int menu_scale_fit_xy = 2131165200;
			
			// aapt resource value: 0x7f070015
			public const int menu_scale_random = 2131165205;
			
			// aapt resource value: 0x7f070014
			public const int menu_scale_random_animate = 2131165204;
			
			// aapt resource value: 0x7f070011
			public const int menu_scale_scale_center = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int menu_scale_scale_center_crop = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int menu_scale_scale_center_inside = 2131165203;
			
			// aapt resource value: 0x7f07000c
			public const int menu_zoom_toggle = 2131165196;
			
			// aapt resource value: 0x7f070006
			public const int myButton = 2131165190;
			
			// aapt resource value: 0x7f070009
			public const int myShareButton = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int snapButton = 2131165194;
			
			// aapt resource value: 0x7f070007
			public const int spinner1 = 2131165191;
			
			// aapt resource value: 0x7f070004
			public const int tv_current_matrix = 2131165188;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int main_menu = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int country_prompt = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int main_krnls = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
